#

version: "3.4"
services:
    mongo:
        image: mongo:3.6.5
        volumes:
            - ./volumes/mongo-data/:/data/db/:rw
        command: --auth
        ports:
            - 127.0.0.1:42017:27017
        restart: always
    api:
        build: images/api
        volumes:
            - ./../lib/:/api/lib/:ro
            - ./../node_modules/:/api/node_modules/:ro
            - ./../public/:/api/public/:ro
            - ./../api.js:/api/api.js:ro
            - ./../conf.json:/api/conf.json:ro
            - ./../package.json:/api/package.json:ro
        environment:
            - NODE_PATH=/api
            - NODE_ENV=production
        command: nodemon --verbose --ext js,json --watch /api api.js
        ports:
            - 127.0.0.1:42080:42080
        restart: always
